### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by shMatrix** [hawtkin/Dell_Latitude_E5470_Hackintosh#1]
Hey there,
First of all thanks a lot for sharing that preconfigured EFI.
This is my first try and I could miss something but I carefully followed all provided guides.
-Downloaded Monterey (also tried BigSur) BaseSystem.dmg and chunklist, put in com.apple.recovery.boot
-Downloaded your EFI, Generated new SMBIOS (tried MacBook9,1 and MacBookPro13,3) and applied to Config.plist
-Update my BIOS configuration as indicated
Trying to boot and see OC boot menu (attached) and nothing happens next. It doesn't stuck, I can press Enter or type 1,2, reboot, etc but nothing happens after it, like it can't boot OS. 
Is there something that I'm doing wrong?
My configuration is slightly different - CPU i5-6440HQ, HD530, RAM 16GB, but I don't think this could cause the issue. 
![photo_2024-06-25_13-57-34](https://github.com/hawtkin/Dell_Latitude_E5470_Hackintosh/assets/5987924/1a72ff5f-45dc-4a4d-8354-f7d5b063ef66)

**Comment by hawtkin** [comment]
Have you tried press [space bar] to show hidden entries?
What happen when you select that NO NAME entry?
![Screenshot 2024-06-25 at 7 54 38 PM](https://github.com/hawtkin/Dell_Latitude_E5470_Hackintosh/assets/72366881/c5d1eac5-a5cb-4ef9-8b94-2432220e8c2e)

**Comment by shMatrix** [comment]
Ok, it started to boot, but now it stuck on bellow screen.
And looks like the system is completely frozen, I can't reboot or anything, only force shutdown helps.
![1](https://github.com/hawtkin/Dell_Latitude_E5470_Hackintosh/assets/5987924/624d0a80-073a-495f-9a2b-5b0330056ca4)

**Comment by hawtkin** [comment]
Oh, i know the problem here, my config.plist has a mistake
Go to Kernel->Quirks in config plist then set AppleXcpmCfgLock to true and AppleCpuPmCfgLock to false
Reboot and try again

**Comment by shMatrix** [comment]
oh man, you are my hero
it works!
Finally I can try to install it to my laptop.
BTW, could you please advice the best SMBIOS for our E5470?

**Comment by hawtkin** [comment]
Your cpu is i5-6440HQ with quad cores and HD530 so MacBookPro13,3 is the best for you.
If you want to try ventura, use Kaby Lake SMBIOS
![Screenshot 2024-06-25 at 10 07 58 PM](https://github.com/hawtkin/Dell_Latitude_E5470_Hackintosh/assets/72366881/9e86830d-1ba3-4873-9c5b-b6921d96297f)

**Comment by shMatrix** [comment]
Got it.
Thank you for your work and sharing it with the world.

**Comment by hawtkin** [comment]
You're welcome! If you have any question or problem, feel free to ask me.
And thanks for helped me found out that mistake in the config.plist
