### ISSUE TITLE
USB 3.0 Support

### ISSUE THREAD

**Issue by shMatrix** [hawtkin/Dell_Latitude_E5470_Hackintosh#2]
Hello again.
So, it works well and pretty stable, no major issues.
Only one thing that I noticed so far - usb ports work in 2.0 mode
Is it fixable? Or USB 3.0 is not supported in our case?

**Comment by hawtkin** [comment]
Hi, thanks for providing the feedback.
And USB 3.0, unfortunately, I don't have any USB 3.0 device around so I don't know if it works or not, but you can try mapping USB yourself using [USBToolBox](https://github.com/USBToolBox/tool) and [this guide](https://www.reddit.com/r/hackintosh/comments/ta1ef4/guide_easy_usb_mapping_with_usbtoolbox_on_windows/)
When you get the working USB3.0 map kext, you can share it to me and I will include it in this repo!

**Comment by shMatrix** [comment]
[UTBMap.kext.zip](https://github.com/user-attachments/files/16034188/UTBMap.kext.zip)

I have 3 usb ports and all of them are USB 3.0
with this kext works in 3.0 mode
thank you for guides

**Comment by hawtkin** [comment]
Wonderful! Thank you for contributing
