### ISSUE TITLE
update to sonoma?

### ISSUE THREAD

**Issue by Mister20143** [hawtkin/Dell_Latitude_E5470_Hackintosh#3]
Hi friend, do you think you could update it to the latest version? 15.0

**Comment by hawtkin** [comment]
Yes, it is possible to run Sonoma on this machine, but I'm still busy with school so I can't update at the moment.
You can try these guide I followed to install Sonoma on this machine, and it works smoothly
Basically, you need to [mod your bios to increase DVMT allocated size to 64mb](https://www.tonymacx86.com/threads/guide-broadwell-hd5500-setting-dvmt-in-insydeh20-bios-laptops.165104/) so you don't need to patch your iGPU in config (you can framebuffer patch like normal but the graphics look terrible)
Then use OCLP to get hardware accel to work. Also some spoofing stuffs to trick new macos run on old mac in [this guide](https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Guides/Skylake.md)
You can still ask me if you have any problem! I will update a guide for mac sonoma when i'm free from school.
![Screenshot 2024-10-25 at 8 29 19 PM](https://github.com/user-attachments/assets/d699e526-420a-4737-abb0-1d78bf0b8a17)

**Comment by Mister20143** [comment]
I already installed it and it worked!!! But the problem is that the wifi and bluetooth don't work, I tried with your .kents and nothing, the latest versions and nothing! :(
![Screenshot 2024-10-26 at 9 36 24 a m](https://github.com/user-attachments/assets/ff415599-77e2-43ef-a88c-7c60fdedfa10)
![Screenshot 2024-10-26 at 9 38 37 a m](https://github.com/user-attachments/assets/8b76df0f-b27d-4f0b-a183-a5661f6f154b)
![Screenshot 2024-10-26 at 9 39 18 a m](https://github.com/user-attachments/assets/991e39e3-fda7-4b0e-bcce-7235b6664da1)
![Screenshot 2024-10-26 at 9 39 41 a m](https://github.com/user-attachments/assets/ee050727-e2fb-4368-af8e-30d92dd847bb)

**Comment by Mister20143** [comment]
I already installed it and it works!!! But the problem is that the wifi and bluetooth don't work, I tried with your .kents and nothing, the latest versions and nothing! :(
![Screenshot 2024-10-26 at 9 36 24 a m](https://github.com/user-attachments/assets/94b9bf1e-1412-4a8a-99f4-0179a10cd2a5)
![Screenshot 2024-10-26 at 9 38 37 a m](https://github.com/user-attachments/assets/9de51b69-926c-4e70-990a-f60fd93423a9)
![Screenshot 2024-10-26 at 9 39 18 a m](https://github.com/user-attachments/assets/033a8ba0-cb47-4085-b937-489211c1c07e)
![Screenshot 2024-10-26 at 9 39 41 a m](https://github.com/user-attachments/assets/dec9a534-07dc-4bfe-be78-3b94444c4992)

**Comment by hawtkin** [comment]
That's wonderful! For wifi, have you set SecureBootModel to `Default` in Misc>Security because AirportItlwm.kext won't work with SecureBootModel `Disabled`. Type `kextstat | grep -i "itlwm"` in terminal to check if itlwm kext is loaded
![Screenshot 2024-10-27 at 9 36 44 AM](https://github.com/user-attachments/assets/68ae29c5-cb98-49a9-8111-840411404cf0)

**Comment by Mister20143** [comment]
Okay, it seems that it is not starting, the SecureBootModel was by default, I already changed it to disabled, I restarted it, but the .kext still does not start
![Screenshot 2024-10-26 at 7 49 24 p m](https://github.com/user-attachments/assets/d55b8c0c-4894-4973-b1a4-56c5d17db688)

**Comment by hawtkin** [comment]
You need to set SecureBootModel to `Default`. And to make sure, have you choose the correct version of [Airportitlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0)? There are separate kexts for different mac versions.
![Screenshot 2024-10-27 at 6 33 47 PM](https://github.com/user-attachments/assets/3b30cb1f-c8a8-4e78-a250-75c6a13340f9)

**Comment by Mister20143** [comment]
I already set the SecureBootModel to default, and the version of Airportitlwm that I used is 14.4, although I have the Mac version 14.7
edit: I don't know when but the bluetooth is already working

**Comment by hawtkin** [comment]
Ohh, that's weird. I'm using macos 14.7 with that 14.4 kext too and it works normally. Maybe you should try booting in any windows os like hirenboot cd pe to check if your wifi card is working.
Or disable that airport kext and use itlwm with heliport app
Or compare your config with mine [here](https://drive.google.com/file/d/1P9Inf9a_VCQbX7bROZkBWms05FuFlAcK/view?usp=drive_link)

**Comment by Mister20143** [comment]
Thank you very much, it worked. I just copied all your kexts, replaced them and that's it, everything works. Thank you very much <3

**Comment by hawtkin** [comment]
Glad to hear that! I don't know why but at least it works for you. Enjoy your hackintosh!
